language: node_js
node_js:
- "stable"

before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
 - npm install codeclimate-test-reporter istanbul -g
  - codeclimate-test-reporter < ./coverage/lcov.info


script: npm test

